export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const FORM_ERROR = 'FORM_ERROR';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';